# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(gradle)"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(npm)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(github-actions)"

  # https://github.com/dependabot/dependabot-core/issues/5137
  - package-ecosystem: "github-actions"
    directory: ".github/actions/gradle"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(github-actions)"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/java"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(github-actions)"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/npm"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(github-actions)"
