name: "setup JDK"
description: "setup JDK"
runs:
  using: "composite"
  steps:
    - name: setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"
