name: "check verification metadata diff"
description: "check verification-metadata.xml's diff"
runs:
  using: "composite"
  steps:
    - name: check verification-metadata.xml
      shell: bash
      run: |
        if [ -n "$(git diff --name-only HEAD | grep -Fx gradle/verification-metadata.xml)" ]; then
          echo "::error::verification-metadata.xml has updates. Please run check and commit the changes";
          echo "$(git status --porcelain)" | while read -r l; do echo "::error::$l"; done;
          exit 1
        else
          echo "::notice::verification-metadata.xml is up-to-date";
        fi
