name: "setup gradle"
description: "setup gradle"
inputs:
  dependency-graph:
    description: |
      Specifies if a GitHub dependency snapshot should be generated for each Gradle build, and if so, how.
      Valid values are 'disabled' (default), 'generate', 'generate-and-submit', 'generate-and-upload', and 'download-and-submit'.
    required: false
    default: "disabled"
  toolchain:
    description: |
      if provides true, run `gradlew -q javaToolchains`
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: setup gradle cache limit
      shell: bash
      run: |
        mkdir -p ~/.gradle/init.d \;
        \cp -rf ./.github/actions/gradle/cache-settings.gradle ~/.gradle/init.d \;

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        cache-cleanup: always
        dependency-graph: ${{ inputs.dependency-graph }}

    - name: list toolchain
      if: ${{ inputs.toolchain == 'true' }}
      shell: bash
      run: |
        ./gradlew -q javaToolchains
