name: stability

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: gradle/actions/dependency-submission@v4
        with:
          gradle-version: wrapper
          dependency-resolution-task: 'resolveAllDependencies'
          validate-wrappers: true

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: check publish task
        shell: bash
        run: |
          ./gradlew publishReleasePublicationToLocalRepository --scan

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        module: [ "webauthn2-json-moshi", "webauthn2-json-serialization" ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: unit test
        shell: bash
        run: |
          ./gradlew :${{ matrix.module }}:testDebugUnitTest --scan
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          check_name: ${{ matrix.module }}
          files: |
            **/test-results/**/*.xml
      - name: jacoco
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          ./gradlew :${{ matrix.module }}:jacoco --scan
      - uses: madrapps/jacoco-report@v1.7.2
        if: ${{ !cancelled() }}
        with:
          paths: |
            ${{ github.workspace }}/${{ matrix.module }}/build/reports/jacoco/jacoco/jacoco.xml
          title: ${{ matrix.module }}
          update-comment: true
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: check api file
        shell: bash
        run: |
          ./gradlew apiCheck --scan

  fixture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm
      - name: config git
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]" && git config --global user.email github-actions-bot@users.noreply.github.com
      - name: re-generate fixture json
        shell: bash
        run: |
          rm -f ./webauthn2-json-core/src/test/resources/*.json;
          npm run exec;
          cp -f ./fixture/json/*.json ./webauthn2-json-core/src/test/resources;
          git add .;
      - name: check fixture diff
        shell: bash
        run: |
          if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
            echo "::error::Fixture json files are not up-to-date. Please run 'npm run exec' and commit the changes";
            echo "$(git status --porcelain)" | while read -r l; do echo "::error::$l"; done;
            exit 1
          else
            echo "::notice::Fixture json files are up-to-date";
          fi
